[package]
name = "onvp-backend"
version = "0.1.0"
edition = "2021"

[dependencies]

chrono = { version = "0.4.38", features = ["serde"] }
diesel = { version = "2.2.3", features = ["postgres", "r2d2", "chrono"] }
clap = { version = "4.5.16", features = ["env", "derive", "color"] }
actix-web = { version = "4.9.0", features = ["rustls", "compress-gzip"] }
utoipa = { version = "4.2.3", features = ["actix_extras"] }
utoipa-rapidoc = { version = "4.0.0", features = ["actix-web"] }
env_logger = { version = "0.11.5" }
serde = { version = "1.0.209", features = ["derive"] }
serde_json = { version = "1.0.127" }
dotenv = { version = "0.15.0" }
rand = "0.8.5"
